<#
.SYNOPSIS
    Creates a new custom persona for the project.

.DESCRIPTION
    Generates a new persona file in the custom/ directory.
    Follows the Prompt OS persona structure.

.PARAMETER Name
    Name of the persona (kebab-case, e.g. 'security-auditor')

.PARAMETER Role
    Role description (e.g. 'Expert in Cybersecurity')

.PARAMETER Force
    Overwrite existing persona

.EXAMPLE
    .\add-persona.ps1 -Name security-auditor -Role "Cybersecurity Expert"

.NOTES
    Version: 3.5.0
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$Name,
    
    [Parameter()]
    [string]$Role = "Custom Role",
    
    [Parameter()]
    [switch]$Force
)

# Configuration
$PersonasDir = Resolve-Path (Join-Path $PSScriptRoot "..\personas")
$CustomDir = Join-Path $PersonasDir "custom"
$PersonaFile = Join-Path $CustomDir "$Name.md"

# Banner
Write-Host "`n🎭 ADD-PERSONA v3.5.0" -ForegroundColor Cyan
Write-Host "======================`n" -ForegroundColor Cyan

# Ensure Directory
if (-not (Test-Path $CustomDir)) {
    New-Item -ItemType Directory -Path $CustomDir -Force | Out-Null
    Write-Host "📁 Created custom directory: $CustomDir" -ForegroundColor Gray
}

# Check Existence
if (Test-Path $PersonaFile -and -not $Force) {
    Write-Host "❌ Error: Persona '$Name' already exists." -ForegroundColor Red
    exit 1
}

# Content Generation
$today = Get-Date -Format "yyyy-MM-dd"

$content = @"
---
name: $Name
role: $Role
version: "1.0.0"
created: $today
type: persona
category: custom
---

# Persona: $Name

> **Role:** $Role

## 🧠 Core Competencies
- [Skill 1]
- [Skill 2]
- [Skill 3]

## 📋 Responsibilities
1. Responsibility A
2. Responsibility B

## 🔄 Interaction Style
- Tone: Professional
- Verbosity: Medium

---

**Generated by Prompt OS**
"@

# Write File
try {
    Set-Content -Path $PersonaFile -Value $content -Encoding UTF8
    Write-Host "✅ Persona created: personas\custom\$Name.md" -ForegroundColor Green
    
    Write-Host "`n🚀 Next Steps:" -ForegroundColor Cyan
    Write-Host "   1. Edit the file to add skills" -ForegroundColor White
    Write-Host "   2. Register in INDEX.md (optional)" -ForegroundColor White
} catch {
    Write-Host "❌ Failed to create persona: $_" -ForegroundColor Red
    exit 1
}
