<#
.SYNOPSIS
    Adds a new AI agent configuration to the project.

.DESCRIPTION
    Creates a specific configuration file for a new AI agent (e.g. mistral.md, deepseek.md).
    This allows multiple agents to work on the same project with specific contexts.

.PARAMETER Name
    Name of the agent (e.g. mistral, deepseek, llama)

.PARAMETER Force
    Overwrite existing configuration if present

.EXAMPLE
    .\add-agent.ps1 -Name deepseek

.NOTES
    Version: 3.5.0
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$Name,
    
    [Parameter()]
    [switch]$Force
)

# Configuration
$ProjectRoot = Get-Location
$AgentFile = Join-Path $ProjectRoot "$Name.md"

# Banner
Write-Host "`n🤖 ADD-AGENT v3.5.0" -ForegroundColor Cyan
Write-Host "====================`n" -ForegroundColor Cyan

# Check existence
if (Test-Path $AgentFile -and -not $Force) {
    Write-Host "❌ Error: Agent configuration '$Name.md' already exists." -ForegroundColor Red
    Write-Host "   Use -Force to overwrite." -ForegroundColor Yellow
    exit 1
}

# Template Content
$today = Get-Date -Format "yyyy-MM-dd"
$projectName = Split-Path $ProjectRoot -Leaf

$content = @"
# $($Name.ToUpper()) - Configuration

**Project:** $projectName
**Date:** $today
**Status:** Active

---

## Instructions for $($Name.ToUpper())

This file contains specific optimization rules for $Name.

### Capabilities
- [ ] Reasoning
- [ ] Code Generation
- [ ] Creative Writing

### Specialized Commands
- (Add specific commands here)

---

**Generated by Prompt OS v3.5.0**
"@

# Create File
try {
    Set-Content -Path $AgentFile -Value $content -Encoding UTF8
    Write-Host "✅ Agent configuration created: $Name.md" -ForegroundColor Green
    
    # Update Signature/Memory optional logic here
    Write-Host "`n🚀 Next Steps:" -ForegroundColor Cyan
    Write-Host "   1. Open $Name.md and customize capabilities" -ForegroundColor White
    Write-Host "   2. Start using the agent: #init --ia $Name" -ForegroundColor White
} catch {
    Write-Host "❌ Failed to create file: $_" -ForegroundColor Red
    exit 1
}
